// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv6-0HzHqPbGQffn353Sk1pF-zEWhqEOM',
    appId: '1:68854093377:web:cf7066668adeba562818c0',
    messagingSenderId: '68854093377',
    projectId: 'garagefinder-6ab05',
    authDomain: 'garagefinder-6ab05.firebaseapp.com',
    storageBucket: 'garagefinder-6ab05.firebasestorage.app',
    measurementId: 'G-V8R6YJ9FEF',
  );

  //if errors

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1b7o_o4j3mFj3zN6vjqFHqYyN_rDM4U',
    appId: '1:68854093377:android:e8019c8078fc8f452818c0',
    messagingSenderId: '68854093377',
    projectId: 'garagefinder-6ab05',
    storageBucket: 'garagefinder-6ab05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH7TFNDKf59BkdRr9ws0vFWb_2wKa-65A',
    appId: '1:68854093377:ios:73e5c3331b64f8a72818c0',
    messagingSenderId: '68854093377',
    projectId: 'garagefinder-6ab05',
    storageBucket: 'garagefinder-6ab05.firebasestorage.app',
    iosBundleId: 'com.example.garagefinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH7TFNDKf59BkdRr9ws0vFWb_2wKa-65A',
    appId: '1:68854093377:ios:73e5c3331b64f8a72818c0',
    messagingSenderId: '68854093377',
    projectId: 'garagefinder-6ab05',
    storageBucket: 'garagefinder-6ab05.firebasestorage.app',
    iosBundleId: 'com.example.garagefinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv6-0HzHqPbGQffn353Sk1pF-zEWhqEOM',
    appId: '1:68854093377:web:4abca6bb42a850ac2818c0',
    messagingSenderId: '68854093377',
    projectId: 'garagefinder-6ab05',
    authDomain: 'garagefinder-6ab05.firebaseapp.com',
    storageBucket: 'garagefinder-6ab05.firebasestorage.app',
    measurementId: 'G-Z8R0YKM9VQ',
  );
}
